### PR TITLE
Switch to stricter vue-recommended ESLint rule

### PR DESCRIPTION
**Pull request by tomers**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [X] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Thanks for contributing!
Unfortunately, will not merge this because:
 1. It's really bad for beginners as we've seen countless times that they are struggling to keep the pace with all the linting rules
 2. It's easy to switch to the desired setup.

**Comment by tomers** [comment]
> 2. It's easy to switch to the desired setup.

It's not easy when the vanilla code from the template does not pass the vue-recommended rules!
So, could you at least merge the code and comments in the config file, without changing the default setting?

**Comment by tomers** [comment]
I noticed you did committed a fix to keep the eslint happy for all vue plugin rules.
Could you please integrate the minor change I made in `template/.eslintrc.js ` (without changing default level)? I believe it'll be more readable for users. Thanks

**Comment by rstoenescu** [comment]
Yes, indeed. Updated. Thanks!

**Pull request closed without merging**
