### PR TITLE
Add ide-helper generated files into `.gitignore`

### PR DESCRIPTION
**Pull request by panstromek**
Having it directly in starter kit is less error-prone than trying to modify `.gitignore` dynamically from extension.

We have IDE folders here anyway, so I think it is okay to have our ide-helper stuff, too.

### CODE REVIEW

**Comment by rstoenescu** [comment]
Why not add this from the extension itself from its install script? Checking if `.gitignore` exists and does not contain it already then adding the line to it. This would be a good exercise ;) Let me review it when you think it's done.

**Comment by rstoenescu** [comment]
The reason this approach is better is that it ensures devs don't have to spawn a new project folder in order to benefit from it.

**Comment by panstromek** [comment]
yea, It sure is more flexible but I don't feel so good about modifying user files for such a simple case.

I will probably do it anyway, but I can't right now and having it directly here works and doesn't really hurt.

**Comment by panstromek** [comment]
but do as you think ;)

**Comment by rstoenescu** [comment]
Do it. It fits with the App Extension philosophy.

**Pull request closed without merging**
