### PR TITLE
Test Specifications Added in the Quasar Template

### PR DESCRIPTION
**Pull request by Arushi-Jain**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] It's been tested on a Cordova (iOS, Android) app
- [ ] It's been tested on a Electron app
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by nothingismagick** [comment]
@Arushi-Jain - thanks for this PR - would you mind taking a look at the RFC https://github.com/quasarframework/quasar-starter-kit/issues/43 that I just authored about this and how it is planned to integrate it into quasar-cli? 

I would like to move forward on this and would love the collaboration.

**Comment by Arushi-Jain** [comment]
@nothingismagick Please check RWA #43 , I have added the approach i used as a workaround to implementing tests in quasar-cli

**Comment by nothingismagick** [comment]
Great - thankyou! 

While the approach you have taken with this PR is one that might work, we are looking to become more modular, extensible and able to keep dependencies updated with a curated collection of interfacing modules and to that end will begin working on a monorepo called \@quasar-test

Nevertheless, we will need to extend the quasar-starter-kit, and its great that you already have in-depth knowledge of it.

**Comment by Arushi-Jain** [comment]
Well, looking forward to your repo. All the best

**Comment by nothingismagick** [comment]
Can you please remove the code you put in your comment of the RFC and close this PR? I have taken that code and put as an issue here: https://github.com/quasarframework/quasar-test/issues/1

**Pull request closed without merging**
